<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Cura_TestSuite_Login_004</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>fc6ffc50-60ea-41cc-8e68-fcc5421dc2b1</testSuiteGuid>
   <testCaseLink>
      <guid>1f461271-3ce0-460a-86c3-a8b5be95ccc6</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC_Cura_LoginPage_004/TC_Cura_LoginPage_004_01</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>00d2643c-91f2-4d66-92cb-a69f95b6cea8</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/TestData/Cura_Login_TestData2</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>00d2643c-91f2-4d66-92cb-a69f95b6cea8</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>username</value>
         <variableId>5b4ac1a4-b939-4731-80ea-576ebfcf75db</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>00d2643c-91f2-4d66-92cb-a69f95b6cea8</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>password</value>
         <variableId>e8503434-9253-4117-8adb-be4711509d7b</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
